title: JayWok
description: Minecraft Forge Modding
theme: just-the-docs
color_scheme: dark

favicon_ico: "/assets/images/favicon.ico"
url: https://jaywok.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
